DROP TABLE IF EXISTS reservation_seats CASCADE;
DROP TABLE IF EXISTS reservations CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;
DROP TABLE IF EXISTS movies CASCADE;
DROP TABLE IF EXISTS seats CASCADE;
DROP TABLE IF EXISTS theaters CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TYPE IF EXISTS reservation_status;

-- DROP TABLE IF EXISTS schemaversions CASCADE;